version: "3.9"

services:
  app:
    container_name: reddit_scraper
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
